// ===========================
// SPECTRUM PRESETS
// ===========================

const builtInPresets = {
    "outline": {
        name: "Outline Spectrum",
        options: {
            "mode": 4,
            "gradient": "prism",
            "gradientRight": "prism",
            "colorMode": "gradient",
            "sensitivity": 1,
            "alphaBars": false,
            "lumiBars": false,
            "ledBars": false,
            "outlineBars": true,
            "radial": false,
            "roundBars": false,
            "reflexRatio": "0",
            "showScaleX": "1",
            "showScaleY": "0",
            "channelLayout": "single",
            "mirror": "0",
            "freqScale": "log",
            "minFreq": 20,
            "maxFreq": 22000,
            "barSpace": 0,
            "fillAlpha": 0.05,
            "lineWidth": 2.5,
            "radius": 0.3,
            "spinSpeed": 0,
            "fftSize": 8192,
            "smoothing": 0.7,
            "ansiBands": "0",
            "linearAmplitude": "1",
            "weightingFilter": "",
            "gravity": 3.8,
            "peakFade": 750,
            "peakHold": 500,
            "linkGrads": false,
            "splitGrad": false,
            "loRes": false
        }
    },
    "ledbars": {
        name: "Classic LED Bars",
        options: {
            alphaBars: false,
            barSpace: 0.2,
            channelLayout: "single",
            colorMode: "gradient",
            gradient: "classic",
            ledBars: true,
            lumiBars: false,
            outlineBars: false,
            mode: 10,
            radial: false,
            reflexRatio: 0,
            roundBars: false,
            showPeaks: true,
            splitGrad: false,
            fftSize: 8192,
            smoothing: 0.7,
            sensitivity: 1
        }
    },
    "dual": {
        name: "Dual-channel Graph",
        options: {
            channelLayout: "dual-combined",
            fillAlpha: 0.3,
            gradient: "cool",
            gradientRight: "dusk",
            lineWidth: 1,
            mode: 10,
            radial: false,
            reflexRatio: 0,
            showPeaks: false,
            splitGrad: false,
            fftSize: 8192,
            smoothing: 0.7,
            sensitivity: 1
        }
    },
    "bands": {
        name: "Octave Bands + Reflex",
        options: {
            alphaBars: false,
            channelLayout: "single",
            colorMode: "gradient",
            gradient: "rainbow",
            ledBars: false,
            lumiBars: false,
            mode: 6,
            outlineBars: false,
            radial: false,
            reflexRatio: 0.25,
            reflexAlpha: 0.2,
            roundBars: false,
            showPeaks: true,
            showScaleX: true,
            splitGrad: false,
            fftSize: 8192,
            smoothing: 0.7,
            sensitivity: 1
        }
    },
    "radial": {
        name: "Radial Color by Level",
        options: {
            alphaBars: true,
            channelLayout: "single",
            colorMode: "bar-level",
            gradient: "prism",
            ledBars: false,
            lumiBars: false,
            mirror: 0,
            mode: 8,
            outlineBars: false,
            radial: true,
            showPeaks: true,
            splitGrad: false,
            fftSize: 8192,
            smoothing: 0.7,
            radius: 0.3,
            spinSpeed: 0,
            sensitivity: 1
        }
    },
    "round": {
        name: "Round Bars by Index",
        options: {
            alphaBars: false,
            channelLayout: "single",
            colorMode: "bar-index",
            gradient: "apple",
            ledBars: false,
            lumiBars: false,
            mirror: 0,
            mode: 10,
            outlineBars: false,
            radial: false,
            reflexRatio: 0,
            roundBars: true,
            showPeaks: false,
            splitGrad: false,
            fftSize: 8192,
            smoothing: 0.7,
            sensitivity: 1
        }
    },
    "neon": {
        name: "Neon Glow",
        options: {
            mode: 10,
            gradient: "miami",
            colorMode: "gradient",
            alphaBars: true,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: false,
            roundBars: true,
            channelLayout: "single",
            barSpace: 0.3,
            fillAlpha: 0.8,
            lineWidth: 0,
            reflexRatio: 0.4,
            reflexAlpha: 0.2,
            showPeaks: true,
            fftSize: 8192,
            smoothing: 0.8,
            gravity: 4.5,
            peakFade: 500,
            peakHold: 300,
            sensitivity: 1
        }
    },
    "retro": {
        name: "Retro Wave",
        options: {
            mode: 10,
            gradient: "outrun",
            colorMode: "gradient",
            alphaBars: false,
            lumiBars: false,
            ledBars: true,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "single",
            barSpace: 0.1,
            reflexRatio: 0.5,
            reflexAlpha: 1,
            showPeaks: true,
            showScaleX: true,
            fftSize: 4096,
            smoothing: 0.6,
            gravity: 3.0,
            sensitivity: 1
        }
    },
    "minimal": {
        name: "Minimal Lines",
        options: {
            mode: 10,
            gradient: "cool",
            colorMode: "gradient",
            alphaBars: false,
            lumiBars: false,
            ledBars: false,
            outlineBars: true,
            radial: false,
            roundBars: false,
            channelLayout: "single",
            barSpace: 0.5,
            fillAlpha: 0,
            lineWidth: 2,
            reflexRatio: 0,
            showPeaks: false,
            fftSize: 8192,
            smoothing: 0.85,
            sensitivity: 2
        }
    },
    "energy": {
        name: "High Energy",
        options: {
            mode: 5,
            gradient: "rainbow",
            colorMode: "bar-level",
            alphaBars: true,
            lumiBars: true,
            ledBars: false,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "single",
            barSpace: 0.15,
            fillAlpha: 0.9,
            reflexRatio: 0,
            showPeaks: true,
            fftSize: 4096,
            smoothing: 0.5,
            gravity: 5.0,
            peakFade: 300,
            peakHold: 100,
            sensitivity: 2
        }
    },
    "aurora": {
        name: "Aurora Borealis",
        options: {
            mode: 10,
            gradient: "aurora",
            colorMode: "gradient",
            alphaBars: true,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "dual-combined",
            barSpace: 0.2,
            fillAlpha: 0.6,
            lineWidth: 1,
            reflexRatio: 0.3,
            reflexAlpha: 0.15,
            showPeaks: false,
            fftSize: 8192,
            smoothing: 0.9,
            gravity: 2.5,
            sensitivity: 1
        }
    },
    "spiral": {
        name: "Spinning Spiral",
        options: {
            mode: 8,
            gradient: "prism",
            colorMode: "bar-index",
            alphaBars: false,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: true,
            roundBars: true,
            channelLayout: "single",
            barSpace: 0.1,
            radius: 0.25,
            spinSpeed: 5,
            reflexRatio: 0,
            showPeaks: true,
            mirror: 0,
            fftSize: 8192,
            smoothing: 0.75,
            sensitivity: 1
        }
    },
    "mirror": {
        name: "Mirror Effect",
        options: {
            mode: 10,
            gradient: "sunset",
            colorMode: "gradient",
            alphaBars: false,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "single",
            mirror: -1,
            barSpace: 0.15,
            reflexRatio: 0,
            showPeaks: true,
            fftSize: 8192,
            smoothing: 0.7,
            sensitivity: 1
        }
    },
    "fire": {
        name: "Fire & Flames",
        options: {
            mode: 10,
            gradient: "sunset",
            gradientRight: "candy",
            colorMode: "bar-level",
            alphaBars: true,
            lumiBars: true,
            ledBars: false,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "single",
            barSpace: 0.05,
            fillAlpha: 0.95,
            reflexRatio: 0.2,
            reflexAlpha: 0.3,
            showPeaks: true,
            splitGrad: true,
            fftSize: 4096,
            smoothing: 0.6,
            gravity: 4.0,
            sensitivity: 2
        }
    },
    "ocean": {
        name: "Ocean Waves",
        options: {
            mode: 10,
            gradient: "pacific",
            colorMode: "gradient",
            alphaBars: true,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: false,
            roundBars: true,
            channelLayout: "single",
            barSpace: 0.25,
            fillAlpha: 0.7,
            reflexRatio: 0.35,
            reflexAlpha: 0.25,
            showPeaks: false,
            fftSize: 8192,
            smoothing: 0.88,
            gravity: 2.0,
            sensitivity: 1
        }
    },
    "crystal": {
        name: "Crystal Clear",
        options: {
            mode: 4,
            gradient: "prism",
            colorMode: "gradient",
            alphaBars: false,
            lumiBars: false,
            ledBars: false,
            outlineBars: true,
            radial: false,
            roundBars: false,
            channelLayout: "dual-combined",
            barSpace: 0.1,
            fillAlpha: 0.15,
            lineWidth: 3,
            reflexRatio: 0,
            showPeaks: false,
            showScaleX: true,
            fftSize: 16384,
            smoothing: 0.82,
            sensitivity: 1
        }
    },
    "disco": {
        name: "Disco Lights",
        options: {
            mode: 10,
            gradient: "rainbow",
            colorMode: "bar-index",
            alphaBars: false,
            lumiBars: true,
            ledBars: true,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "single",
            barSpace: 0.2,
            reflexRatio: 0.4,
            reflexAlpha: 0.2,
            showPeaks: true,
            fftSize: 4096,
            smoothing: 0.55,
            gravity: 4.5,
            peakFade: 400,
            peakHold: 200,
            sensitivity: 2
        }
    },
    "quantum": {
        name: "Quantum Field",
        options: {
            mode: 8,
            gradient: "shahabi",
            colorMode: "bar-level",
            alphaBars: true,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: true,
            roundBars: false,
            channelLayout: "single",
            radius: 0.35,
            spinSpeed: -3,
            barSpace: 0.05,
            fillAlpha: 0.85,
            showPeaks: true,
            mirror: 0,
            fftSize: 8192,
            smoothing: 0.77,
            sensitivity: 1
        }
    },
    "galaxy": {
        name: "Galaxy Swirl",
        options: {
            mode: 8,
            gradient: "orient",
            colorMode: "gradient",
            alphaBars: true,
            lumiBars: false,
            ledBars: false,
            outlineBars: false,
            radial: true,
            roundBars: true,
            channelLayout: "single",
            radius: 0.2,
            spinSpeed: 8,
            barSpace: 0.15,
            fillAlpha: 0.75,
            reflexRatio: 0,
            showPeaks: false,
            fftSize: 8192,
            smoothing: 0.8,
            sensitivity: 1
        }
    },
    "techno": {
        name: "Techno Beat",
        options: {
            mode: 10,
            gradient: "outrun",
            gradientRight: "miami",
            colorMode: "gradient",
            alphaBars: false,
            lumiBars: false,
            ledBars: true,
            outlineBars: false,
            radial: false,
            roundBars: false,
            channelLayout: "dual-combined",
            barSpace: 0.1,
            splitGrad: true,
            reflexRatio: 0.45,
            reflexAlpha: 0.3,
            showPeaks: true,
            showScaleX: true,
            fftSize: 4096,
            smoothing: 0.65,
            gravity: 3.5,
            sensitivity: 2
        }
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { builtInPresets };
}
